name: Fix Terraform file formatting

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  run:
    permissions:
      contents: write # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    name: Run terraform fmt and terraform-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform fmt
        uses: dflook/terraform-fmt@v2

      - name: Render terraform docs inside the README.md and push changes
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_message: Terraform Fmt
